# Generated by Django 6.0.4 on 2026-09-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0002_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Name of the payer (manual entry)', max_length=100),
        ),
    ]
