# Generated by Django 6.1 on 2026-08-25 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('habanero', 'Habanero Pepper'), ('bell', 'Bell Pepper')], default='habanero', help_text='Type of pepper', max_length=20)),
                ('color', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='red', help_text='Color variety', max_length=10)),
                ('name', models.CharField(help_text="Display name (e.g., 'Red Habanero Pepper')", max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=120, unique=True)),
                ('description', models.TextField(help_text='Detailed description (taste, heat level, uses, etc.)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Per Kilogram'), ('pc', 'Per Piece'), ('bunch', 'Per Bunch')], default='kg', help_text='How is this sold? (e.g., by weight or count)', max_length=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Current available quantity')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to hide product from the store (e.g., out of season)')),
                ('featured_image', models.ImageField(blank=True, help_text='Main product photo', null=True, upload_to='products/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category', 'color'],
                'unique_together': {('category', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as the main thumbnail if featured_image is empty')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
