# Generated by Django 6.1 on 2026-08-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'color', 'grade')},
        ),
    ]
