# Generated by Django 6.1 on 2026-08-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'color', 'grade', 'unit')},
        ),
    ]
