# Generated by Django 6.1 on 2026-08-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Per Kilogram'), ('half_kg', 'Per Half Kg'), ('quarter_kg', 'Per Quarter Kg'), ('pc', 'Per Piece'), ('bunch', 'Per Bunch')], default='kg', help_text='How is this sold? (e.g., by weight or count)', max_length=10),
        ),
    ]
