# Generated by Django 6.1 on 2026-08-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_weight_kg', models.DecimalField(decimal_places=2, default=5.0, help_text='Weight of one crate in kilograms (e.g., 5.00)', max_digits=5)),
                ('single_crate_price', models.DecimalField(decimal_places=2, help_text='Price for 1 crate', max_digits=10)),
                ('two_to_five_crate_price', models.DecimalField(decimal_places=2, help_text='Price per crate when ordering 2-5 crates', max_digits=10)),
                ('six_plus_crate_price', models.DecimalField(decimal_places=2, help_text='Price per crate when ordering 6 or more crates', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active bulk pricing will appear on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The pepper this bulk pricing applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Bulk Pricing',
                'verbose_name_plural': 'Bulk Pricing',
                'ordering': ['product', 'crate_weight_kg'],
                'unique_together': {('product', 'crate_weight_kg')},
            },
        ),
    ]
