# Generated by Django 6.0.4 on 2026-09-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
